### ISSUE TITLE
клонирование репозитория

### ISSUE THREAD

**Issue by Leon6565** [Leon6565/api_yamdb#2]

**Comment by Leon6565** [comment]
Клонирование репозитория, настройка виртуального пространства.

**Comment by MKraynikov** [comment]
Смотри, можно не распыляться на мелкие задачи. Достаточно сделать общий модуль и запилить чек-лист для контроля. Например, как в теории:

issues - управление пользователями

- [ ] Система регистрации и аутентификации
- [ ] Права доступа
- [ ] Работа с токенами
- [ ] Система подтверждения через email
